name: Concurrency Workflow 2

on:
  pull_request:
    branches: concurrency

concurrency: concurrency-workflow-key-2

jobs:
  concurrency-workflow-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Concurrency Workflow 2
        run: echo "Concurrency Workflow 2 Started"

      - name: Run Concurrency Workflow 2
        run: sleep 60
