name: Concurrency Job 2

on:
  pull_request:
    branches: concurrency

concurrency: concurrency-job-key-2

jobs:
  concurrency-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Concurrency Job 2
        run: echo "Concurrency Job 2 Started"

      - name: Run Concurrency Job 2
        run: sleep 60
