name: Pull Request Master Branch

on:
  pull_request:
    branches:
      - master

jobs:
  pull_request-on-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trigger on Pull Request
        run: echo "Testing on master branch"
