name: Section 2 Assignment

on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Test
        run: echo "Testing are running"
      - name: Test Completed
        run: |
          echo "Test completed"
          echo "Building application"
