name: Concurrency Workflow 1

on:
  pull_request:
    branches: concurrency

concurrency: concurrency-workflow-key-1

jobs:
  concurrency-workflow-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Concurrency Workflow 1
        run: echo "Concurrency Workflow 1 Started"

      - name: Run Concurrency Workflow 1
        run: sleep 60
