name: Github Environment

on:
  push:
    branches:
      - master

jobs:
  github-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print Github Environment
        run: echo "GITHUB_ENV is ${{ github }}"
