name: Push Master Branch

on:
  push:
    branches:
      - master

jobs:
  push-on-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Test on Master Branch
        run: echo "Testing on master branch"
